version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
    - 8.2.0
    - 8.3.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
    - 7.25.0
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.1.2
    - 10.2.0
    - 10.3.0
    - 10.4.0
    - 10.4.1
  - dependency-name: "@glimmer/syntax"
    versions:
    - 0.73.2
    - 0.74.0
    - 0.74.2
    - 0.75.0
    - 0.76.0
    - 0.77.1
    - 0.77.3
    - 0.77.4
    - 0.77.5
    - 0.77.6
    - 0.78.0
    - 0.78.2
  - dependency-name: ember-cli
    versions:
    - 3.24.0
    - 3.25.0
    - 3.25.1
    - 3.25.2
    - 3.25.3
    - 3.26.0
    - 3.26.1
  - dependency-name: ssri
    versions:
    - 6.0.2
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.4.0
  - dependency-name: qunit
    versions:
    - 2.15.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
    - 4.0.3
  - dependency-name: node-notifier
    versions:
    - 8.0.2
  - dependency-name: ember-template-lint
    versions:
    - 2.17.0
    - 2.18.0
    - 2.18.1
    - 2.19.0
    - 2.20.0
    - 2.21.0
    - 3.0.0
    - 3.0.1
    - 3.1.1
    - 3.2.0
  - dependency-name: ember-source
    versions:
    - 3.24.1
    - 3.25.0
    - 3.25.1
    - 3.25.3
    - 3.26.0
    - 3.26.1
  - dependency-name: babel-plugin-ember-modules-api-polyfill
    versions:
    - 3.2.1
    - 3.2.2
    - 3.3.0
    - 3.4.0
    - 3.5.0
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: "@glimmer/component"
    versions:
    - 1.0.3
    - 1.0.4
  - dependency-name: "@glimmer/tracking"
    versions:
    - 1.0.3
    - 1.0.4
